import type { BookItem } from "./Book";

export const mockBooks: BookItem[] = [
  {
    id: "bk_001",
    type: "ebook",
    title: "Mastering Next.js 16",
    author: "Rafiul Kabir",
    orderId: "ORD-10234",
    purchaseDate: "2026-08-28",
    price: 890,
    format: "PDF",
    fileSizeMb: 12.4,
    downloadUrl: "/downloads/mastering-nextjs-16.pdf",
  },
  {
    id: "bk_002",
    type: "physical",
    title: "Clean Architecture",
    author: "Robert C. Martin",
    orderId: "ORD-10221",
    purchaseDate: "2026-08-20",
    price: 1450,
    status: "out_for_delivery",
    trackingId: "TRK-88213",
    courier: "Pathao Courier",
    estimatedDelivery: "2026-09-05",
    address: "Chattogram, Bangladesh",
    timeline: [
      { label: "Order confirmed", date: "2026-08-20", completed: true },
      { label: "Packed", date: "2026-08-21", completed: true },
      { label: "Shipped", date: "2026-08-23", completed: true },
      { label: "Out for delivery", date: "2026-09-03", completed: true },
      { label: "Delivered", completed: false },
    ],
  },
  {
    id: "bk_003",
    type: "ebook",
    title: "The Pragmatic Programmer",
    author: "David Thomas, Andrew Hunt",
    orderId: "ORD-10190",
    purchaseDate: "2026-08-10",
    price: 650,
    format: "EPUB",
    fileSizeMb: 6.1,
    downloadUrl: "/downloads/pragmatic-programmer.epub",
  },
  {
    id: "bk_004",
    type: "physical",
    title: "Atomic Habits",
    author: "James Clear",
    orderId: "ORD-10145",
    purchaseDate: "2026-07-30",
    price: 720,
    status: "delivered",
    trackingId: "TRK-77102",
    courier: "Sundarban Courier",
    estimatedDelivery: "2026-08-04",
    address: "Chattogram, Bangladesh",
    timeline: [
      { label: "Order confirmed", date: "2026-07-30", completed: true },
      { label: "Packed", date: "2026-07-31", completed: true },
      { label: "Shipped", date: "2026-08-01", completed: true },
      { label: "Out for delivery", date: "2026-08-04", completed: true },
      { label: "Delivered", date: "2026-08-04", completed: true },
    ],
  },
  {
    id: "bk_005",
    type: "physical",
    title: "Deep Work",
    author: "Cal Newport",
    orderId: "ORD-10102",
    purchaseDate: "2026-07-15",
    price: 590,
    status: "pending",
    address: "Chattogram, Bangladesh",
    timeline: [
      { label: "Order confirmed", date: "2026-07-15", completed: true },
      { label: "Packed", completed: false },
      { label: "Shipped", completed: false },
      { label: "Out for delivery", completed: false },
      { label: "Delivered", completed: false },
    ],
  },
  {
    id: "bk_006",
    type: "ebook",
    title: "Designing Data-Intensive Applications",
    author: "Martin Kleppmann",
    orderId: "ORD-10077",
    purchaseDate: "2026-06-22",
    price: 980,
    format: "PDF",
    fileSizeMb: 18.9,
    downloadUrl: "/downloads/ddia.pdf",
  },
  {
    id: "bk_007",
    type: "physical",
    title: "Sapiens",
    author: "Yuval Noah Harari",
    orderId: "ORD-10022",
    purchaseDate: "2026-06-02",
    price: 810,
    status: "cancelled",
    address: "Chattogram, Bangladesh",
    timeline: [
      { label: "Order confirmed", date: "2026-06-02", completed: true },
      { label: "Cancelled", date: "2026-06-03", completed: true },
    ],
  },
];
